### PR TITLE
chroot: Made main() and usage() declaration at the top of the file ...

### PR DESCRIPTION
**Pull request by takusuman**
insteading of reallocating the functions, so now both us and OpenBSD get happy. :^)

### CODE REVIEW

**Comment by takusuman** [comment]
I think this is just better to read than moving everything before main().
By the way, if you need to test for code consistency, may clang's ``-Weverything`` be a nice option. 😄 
I know it's funny to me to pull-request in a fork of a project that I maintain, but I didn't wanted to change anything in your work in progress without making you aware @mamccollum.
Anyway, have a good night.

**Comment by mamccollum** [comment]
@takusuman Hey there, I'd like to apologize for not responding to this. I've been working a lot recently on IRL stuff and I havent had to chance to get much done here. I hope I didn't come off as ignoring you. I'll look into this as soon as I can.

**Comment by takusuman** [comment]
> @takusuman Hey there, I'd like to apologize for not responding to this. I've been working a lot recently on IRL stuff and I havent had to chance to get much done here. I hope I didn't come off as ignoring you.

Oh, I understand, no problem. I knew you were working on something, so I haven't even thought about it.

> I'll look into this as soon as I can, as it still lets me see the commit despite the repository being gone.

I didn't know deleting the repository could cause this... Sorry.
I haven't configured my "git-pull-request" git module corretly, so it created the Heirloom NG fork on my profile and I decided to delete it. Anyway, I can redo the changes if needed.

**Comment by takusuman** [comment]
In the worst case scenario, I think we can extract the .diff.
Give me a minute.

**Comment by takusuman** [comment]
https://github.com/mamccollum/heirloom-ng/commit/8dfd9399e161a31c34a0fec73eef0066fc23f4e9.diff

Here @mamccollum

**Comment by mamccollum** [comment]
Thank you, I'll take a look when I can. :slightly_smiling_face:

**Comment by takusuman** [comment]
Just a reminder: take a look at this little patch that I've made.

**Comment by mamccollum** [comment]
> Just a reminder: take a look at this little patch that I've made.

Ah yeah, I'll apply the patch in just a minute. I see what it's for now.

**Pull request closed without merging**
